#!/usr/bin/env bash

# [[ -z "$@" ]] && echo "Usage: pdfbates filename.pdf starting-number (default 1) padding-zeros (default 0)" && exit 2

# for file in $1; do
# done

for file in "$@"; do
    printf 'Stamping with page number %s\n' "$file"
    tmp=$(mktemp "$(dirname "$file")/.pdfbates.XXXXXX")
    if cpdf "$file" -add-text "%Bates" -bates "1" -bates-pad-to "0" -bottomright 16 -font "Helvetica" -color "black" -opacity 0.3 -o "$tmp"; then
        mv "$tmp" "$file"
    else
        rm -f "$tmp"
        echo "Error: pdfbates failed on '$file'" >&2
    fi
    # cpdf "$file" -add-text "%Bates" -bates "${2:-1}" -bates-pad-to "${3:-0}" -bottomright 16 -font "Helvetica" -color "black" -opacity 0.3 -o "$file"
done








