#!/usr/bin/env bash

for file in "$@"; do
    printf "$file\n"
    tmp=$(mktemp "$(dirname "$file")/.pdflogo.XXXXXX")
    if cpdf -stamp-on ~/.config/logos/mandarine-logo-small.pdf -topright 10 "$file" all -o "$tmp"; then
        mv "$tmp" "$file"
    else
        rm -f "$tmp"
        echo "Error: pdflogo failed on '$file'" >&2
    fi
done

# stamp pdf with mandarine logo
